### ISSUE TITLE
go vet error on literal copy of a lock value, with go 1.7.3

### ISSUE THREAD

**Issue by ericpromislow** [bitnami/gonit#10]
```
$ make vet
+ vet-utils
+ vet-database
+ vet-testutils
+ vet-monitor
monitor/checks.go:292: literal copies lock value from check: monitor.check contains monitor.syncBool
exit status 1
make: *** [vet-monitor] Error 1
```

**Comment by juamedgod** [comment]
It seems is a false positive:

https://github.com/golang/go/issues/16227

In any case, I will prepare a patch to make go vet happy and take the opportunity to include 1.7 in the travis builds.

Thanks for reporting it!

**Comment by juamedgod** [comment]
Fixed in https://github.com/bitnami/gonit/pull/11
