### ISSUE TITLE
Gonit Arm64/aarch64 Graviton support

### ISSUE THREAD

**Issue by MayurDuduka** [bitnami/gonit#39]
### What is the problem this feature will solve?

```
[root@ip-172-17-** gonit]# nano Makefile
[root@ip-172-17--** gonit]# make build/aarch64
+ Building GOARCH=aarch64
go: unsupported GOOS/GOARCH pair linux/aarch64
make: *** [Makefile:45: build/aarch64] Error 2
[root@ip-172-17--** gonit]# nano Makefile
[root@ip-172-17--** gonit]# make build
+ Building GOARCH=aarch64
go: unsupported GOOS/GOARCH pair linux/aarch64
make: *** [Makefile:45: build/aarch64] Error 2
[root@ip-172-17-** gonit]# nano Makefile
[root@ip-172-17-** gonit]# make build
+ Building GOARCH=amd64
*** Gonit binary created under ./dist/gonit/ ***
[root@ip-172-17-** gonit]# nano Makefile
[root@ip-172-17-** gonit]# make build
+ Building GOARCH=arm64
*** Gonit binary created under ./dist/gonit/ ***
[root@ip-172-17-** gonit]# gonit
Control file '/etc/gonit/gonitrc' does not exists
[root@ip-172-17-** gonit]#
```

### What is the feature you are proposing to solve the problem?

Gonit Arm64/aarch64 Graviton support

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/gonit/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
